### PR TITLE
Switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by ocsw**
Now that travis-ci.org is no more

### CODE REVIEW

**Comment by Jill1627** [comment]
LGTM. but I am not an expert of GH action usages so, thinking might be better that someone else +1.

**Comment by ocsw** [comment]
Not sure any of us is.  I posted in #foss-discuss but I didn't get any responses...

**Comment by larkintuckerllc** [comment]
LGTM; interesting GitHub Actions seems to give you more fine grained control over the build (comparing to Travis).

**Review by mike-at-spotify — APPROVED** [review]
I don't know an awful lot about GH actions, but I looked through this with John, and we think it looks OK.

**Pull request merged**
